ARG SALTCORN_VERSION=1.1.3


FROM node:18.20-alpine3.21

ENV NODE_ENV "production"
ENV SALTCORN_DISABLE_UPGRADE "true"

RUN npm install -g @saltcorn/cli@${SALTCORN_VERSION} --omit=dev

RUN chown -R node:node /usr/local/lib/node_modules

USER node

ENTRYPOINT ["/usr/local/bin/saltcorn"]
