FROM node:18-bullseye

ENV NODE_ENV "production"
ENV SALTCORN_DISABLE_UPGRADE "true"

RUN apt update && apt install -qqy libpq-dev build-essential python-is-python3 postgresql-client git chromium

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD "true"

RUN npm install -g @saltcorn/cli@1.1.3 --omit=dev

ENTRYPOINT ["/usr/local/bin/saltcorn"]
