{{- if and (eq .Values.persistence.type "pvc") (eq .Values.persistence.pvc.existingClaim "") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "saltcorn.fullname" . }}-pvc
  labels:
    app: {{ include "saltcorn.fullname" . }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.pvc.size }}
  storageClassName: {{ .Values.persistence.pvc.storageClassName }}
{{- end }}
