{{- if and (eq .Values.persistence.type "pvc") (eq .Values.persistence.pvc.existingClaim "") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ include "saltcorn.fullname" . }}
  annotations:
    "helm.sh/hook": pre-install
spec:
  accessModes:
    - {{ .Values.persistence.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.pvc.size }}
  storageClassName: {{ .Values.persistence.pvc.storageClassName }}
{{- end }}
