{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "saltcorn.serviceAccountName" . }}
  labels:
    {{- include "saltcorn.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
    "helm.sh/hook": pre-install
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
