image:
  repository: protonalialol/saltcorn
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

replicaCount: 1
debugReplicaCount: 0

server:
  debug: false

persistence:
  type: "pvc" # Valid options: "pvc" or "postgresql"

  pvc:
    existingClaim: ""
    size: 1Gi
    accessMode: ReadWriteOnce
    storageClassName: "local-path"

  postgresql:
    pgUser: "admin"
    pgPassword: "admin"
    pgHost: "postgresql.postgresql.svc.cluster.local"
    pgPort: "5432"
    pgDatabase: "saltcorn"

env:
  - name: NODE_OPTIONS
    value: --max-old-space-size=512

resources:
  limits:
    cpu: 1
    memory: 2048Mi
  requests:
    cpu: 100m
    memory: 512Mi

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  runAsNonRoot: true
  runAsUser: 1000
  seccompProfile:
    type: RuntimeDefault

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - host: saltcorn-18.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: saltcorn-tls
      hosts:
        - saltcorn.local

route:
  enabled: false
  host: "saltcorn-dev.local"
  tls:
    termination: "edge"
    insecureEdgeTerminationPolicy: "Allow"

volumes: []

volumeMounts: []

command: []

args: []

nodeSelector: {}

tolerations: []

affinity: {}
