name: docker-ci

on:
  push:

jobs:
  docker-release:
    if: false
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.release
          push: true
          tags: ${{ github.repository }}:release

  docker-light:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [18.20, 20.19, 22.14]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          build-args: |
            NODE_BASE_IMAGE=${{ matrix.node_version }}-alpine3.21
            SALTCORN_VERSION=1.1.3
          context: .
          file: Dockerfile.light
          push: true
          tags: ${{ github.repository }}:light-${{ matrix.node_version }}